#+Title: Kickstart.emacs
#+Author: Christoffer
#+Description: Blazingly fast starting point for your Emacs configuration.
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents :toc:
- [[#introduction][Introduction]]
  - [[#what-is-kickstartemacs][What is Kickstart.emacs?]]
  - [[#ctrl--meta][Ctrl & Meta]]
  - [[#where-to-start][Where to start?]]
  - [[#getting-help][Getting Help]]
- [[#core-setup--performance][Core Setup & Performance]]
  - [[#startup-performance][Startup Performance]]
  - [[#auto-tangle-configuration-file][Auto-tangle Configuration file]]
  - [[#show-startup-time][Show startup time]]
  - [[#package-manager][Package manager]]
  - [[#good-defaults][Good Defaults]]
- [[#important-to-load-first][Important to load first]]
  - [[#evil-mode][Evil Mode]]
  - [[#general-keybindings][General Keybindings]]
  - [[#undo][Undo]]
- [[#appearance][Appearance]]
  - [[#fonts][Fonts]]
  - [[#frame-size][Frame Size]]
  - [[#set-theme][Set Theme]]
  - [[#transparency][Transparency]]
  - [[#doom-modeline][Doom Modeline]]
  - [[#nerd-icons][Nerd Icons]]
- [[#development][Development]]
  - [[#projectile][Projectile]]
  - [[#eglot][Eglot]]
  - [[#masonel][Mason.el]]
  - [[#eldoc-box][Eldoc Box]]
  - [[#sideline-flymake][Sideline-flymake]]
  - [[#yasnippet][Yasnippet]]
  - [[#snippy][Snippy]]
  - [[#tree-sitter][Tree-Sitter]]
  - [[#language-modes][Language modes]]
  - [[#terminal][Terminal]]
- [[#multi-file-example][Multi File Example]]
  - [[#adding-the-lisp-directory-to-load-path][Adding the lisp directory to load-path]]
  - [[#sourcing-the-files][Sourcing the files]]
  - [[#using-the-file][Using the file]]
- [[#version-control][Version Control]]
  - [[#magit][Magit]]
  - [[#diff-hl][Diff-hl]]
- [[#completion][Completion]]
  - [[#corfu][Corfu]]
  - [[#cape][Cape]]
  - [[#orderless][Orderless]]
  - [[#vertico-and-marginalia][Vertico and Marginalia]]
  - [[#embark][Embark]]
  - [[#jinx][Jinx]]
  - [[#gptel][GPTel]]
  - [[#copilot][Copilot]]
- [[#other-packages][Other packages]]
  - [[#consult][Consult]]
  - [[#helpful][Helpful]]
  - [[#diminish][Diminish]]
  - [[#rainbow-delimiters][Rainbow Delimiters]]
  - [[#hl-todo][Hl-todo]]
  - [[#indent-guide][Indent-guide]]
  - [[#which-key][Which-Key]]
  - [[#ws-butler][Ws-butler]]
  - [[#esup][Esup]]
  - [[#ag][ag]]

* Introduction
#+begin_src emacs-lisp :tangle no
    ;;==================================================================;;
    ;;================== READ THIS BEFORE CONTINUING ===================;;
    ;;==================================================================;;
    ;;======                                    .-----.          =======;;
    ;;======         .----------------------.   | === |          =======;;
    ;;======         |.-""""""""""""""""""-.|   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         ||  'KICKSTART.EMACS' ||   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         || M-X:               ||   |-----|          =======;;
    ;;======         || help-with-tutorial ||   |:::::|          =======;;
    ;;======         |'-..................-'|   |____o|          =======;;
    ;;======         `"")----------------(""`   ____________     =======;;
    ;;======        /::::::::::|  |:::::p::::\  \ Only CTRL \    =======;;
    ;;======       /:::=======f|  |========:::\  \ required  \   =======;;
    ;;======      'CTRL""""""""'  'bn""""""""""'  '""""""""""'   =======;;
    ;;======                                                     =======;;
    ;;==================================================================;;
    ;;==================================================================;;
#+end_src

** What is Kickstart.emacs?
Kickstart.emacs is *not* a distribution.
It's a template for your own configuration.
Inspired by kickstart.nvim.

It is *recommended* to configure it from the *init.org* file.

Kickstart.emacs is a starting point for your own configuration.
The goal is that you read every line, top-to-bottom, understand
what your configuration is doing, and modify it to suit your needs.

After you've done that, you can start making your own configuration out of this
or taking the things you like and making something new from scratch.
The choice is yours. You can do basically anything with Emacs.
So don't hesitate to try things out.

You can delete this when you're done. It's your config now. :)
I hope you have fun with your Emacs journey.
MiniApollo

** Ctrl & Meta
This is from the Emacs tutorial, but I put this here for safety.

Emacs commands generally involve the CONTROL key (often labeled CTRL)
or the META key (usually labeled ALT). Rather than writing that
in full each time, we'll use the following abbreviations:

C-<chr>  means hold the CONTROL key while typing the character <chr>.
Thus, C-f would be: hold the CONTROL key and type f.
M-<chr>  means hold the META or ALT key down while typing <chr>.
If there is no META or ALT key, instead press and release the
ESC key and then type <chr>.  We write <ESC> for the ESC key.

** Where to start?
First I recommend starting with the Emacs tutorial with the following keybinding: C-h t
Or running the command with M-x: help-with-tutorial
Even if you plan on using Vim keybindings later on, it's a good idea to learn the standard Emacs keybindings.
If you already know the standard Emacs keybindings, you can skip this step.

After you completed that, you should start learning Emacs lisp.
It is not necessary to know elisp, but I recommend it. It will open up a whole new world, trust me.
I used Emacs and Neovim without knowing much about the core language and just copy pasting packages or plugins.
But after learning the fundamentals you can customize basically anything and I really mean ANYTHING.

This will look daunting at first, but don't be scared. This is why I am here.
Elisp is not harder than lua or any other language.

If you don't know anything about elisp, I recommend taking some time to read through
a guide. One possible example which will only take 10-15 minutes:
https://learnxinyminutes.com/elisp/

Or if you want to know everything about elisp:
https://www.gnu.org/software/emacs/manual/html_node/eintr/

** Getting Help
If you get stuck or confused about something, you're in luck:
Because Emacs has a really good help functionality.
Everything under C-h is used for help keybindings.

Using the following keybind: C-h C-h
Or running the following command M-x: help-for-help
Will open up the Emacs help for help menu (I know it's a really creative name :D).
This is the central place where you can see all possible commands you can use when you are stuck.

The most used commands for me are:
- C-h v Describe variable
- C-h f Describe function
- C-h k Describe key

Other also really useful ones:
- C-h i Show all installed manuals
- C-h r Emacs manual
- C-h a Search for commands (see also M-x: Apropos)
- C-h m Show help for current major and minor modes

These commands should be the first thing you use when you're stuck or confused with something.

*** Searching the manual
The manual has a specific mode called info-mode.
Which has useful features you can use.
For more about info-mode: C-h f: info-mode

Basic navigation:
- d key: Go back to the top-level Info Directory.
- u key: Go up to the parent node in the document's hierarchy.
- n key: for next node in the current manual.
- p key: for previous node in the current manual.

*Note:* A Node is essentially a specific section or topic, much like a chapter or subsection in a book.

When you are browsing through the Emacs manual you can easily search with:
- i key: for specific subjects in the current manual.
- g key: for nodes (sections).
- m key: for menu items within the current Info buffer.
- s key: for regular expression patterns (like words) within the current Info buffer.

For evil users after setting up evil collection for info mode:
- g-j: for next node in the current manual.
- g-k: for previous node in the current manual.
- g-G: for nodes (sections).
- g-m: for menu items within the current Info buffer.
- The other keybinds are the same
To see all the evil [[https://github.com/emacs-evil/evil-collection/blob/master/modes/info/evil-collection-info.el][keybindings]] for info mode.

Using goto-node:
- Specify a Manual: If you want to search within a particular manual, place its name in parentheses like (emacs).
- After that tell where you want to go in that manual. For example (emacs)Top, (emacs)specific section.
- If you don't type a manual name, goto-node will search the currently opened manual.

* Core Setup & Performance
These are essential settings and small tweaks that must load before any packages.
They impact the entire configuration, skipping these could result in significantly slower configuration and potential breakage of your setup.

** Startup Performance
Core performance tweaks moved to early-init.el
See: [[https://github.com/doomemacs/doomemacs/issues/310][Why is doom emacs so fast?]]

*** Lexical-bindings
Gives better performance, lexical closures, and code safety, allowing local variables to remain truly local.
#+begin_src emacs-lisp
    ;; -*- lexical-binding: t; -*-
#+end_src

*** Early-Init.el
This file is loaded before anything else.
Most of the performance tweaks are there.
We can configure things before the GUI or other packages are loaded.

** Auto-tangle Configuration file
Auto-Tangle Org configuration file so init.el stays in sync with this document.

If you like to auto tangle an Org file, don't forget to add the following line to the top of your Org document:
(#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the init.el file won't update on change!
To fix this, you need to find this file (C-x C-f), fix the error and press C-c C-v t to tangle it manually.

This snippet adds a hook to org-mode buffers so that start/org-babel-tangle-config gets executed each time such a buffer gets saved.
This function checks to see if the file being saved is the init.org file you’re looking at right now, and if so,
automatically exports the configuration here to the associated output files.
#+begin_src emacs-lisp
    (defun start/org-babel-tangle-config ()
      "Automatically tangle our init.org config file when we save it. Credit to Emacs From Scratch for this one!"
      (interactive)
      (when (string-equal (file-name-directory (buffer-file-name))
                          (expand-file-name user-emacs-directory))
        ;; Dynamic scoping to the rescue
        (let ((org-confirm-babel-evaluate nil))
          (org-babel-tangle)
          )))

    (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-config)))
#+end_src

** Show startup time
#+begin_src emacs-lisp
    (defun start/display-startup-time ()
      (interactive)
      (message "Emacs loaded in %s with %d garbage collections."
               (format "%.2f seconds"
                       (float-time
                        (time-subtract after-init-time before-init-time)))
               gcs-done))

    (add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

** Package manager
We use [[https://github.com/progfolio/elpaca][Elpaca]] as package manager.

Elpaca:
- Installs packages asynchronously.
- Uses source repos directly.
- Includes a package management UI.

Useful commands:
- M-x elpaca-manager
- M-x elpaca-fetch-all
- M-x elpaca-merge-all
- M-x elpaca-update-all
- M-x elpaca-log

*** Elpaca bootstrap
This is the installer from the Elpaca README.
#+begin_src emacs-lisp
    (defvar elpaca-installer-version 0.11)
    (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
    (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
    (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
    (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                  :ref nil :depth 1 :inherit ignore
                                  :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                  :build (:not elpaca--activate-package)))
    (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
           (build (expand-file-name "elpaca/" elpaca-builds-directory))
           (order (cdr elpaca-order))
           (default-directory repo))
      (add-to-list 'load-path (if (file-exists-p build) build repo))
      (unless (file-exists-p repo)
        (make-directory repo t)
        (when (<= emacs-major-version 28) (require 'subr-x))
        (condition-case-unless-debug err
            (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                      ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                      ,@(when-let* ((depth (plist-get order :depth)))
                                                          (list (format "--depth=%d" depth) "--no-single-branch"))
                                                      ,(plist-get order :repo) ,repo))))
                      ((zerop (call-process "git" nil buffer t "checkout"
                                            (or (plist-get order :ref) "--"))))
                      (emacs (concat invocation-directory invocation-name))
                      ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                            "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                      ((require 'elpaca))
                      ((elpaca-generate-autoloads "elpaca" repo)))
                (progn (message "%s" (buffer-string)) (kill-buffer buffer))
              (error "%s" (with-current-buffer buffer (buffer-string))))
          ((error) (warn "%s" err) (delete-directory repo 'recursive))))
      (unless (require 'elpaca-autoloads nil t)
        (require 'elpaca)
        (elpaca-generate-autoloads "elpaca" repo)
        (let ((load-source-file-function nil))
          (load "./elpaca-autoloads"))))
    (add-hook 'after-init-hook #'elpaca-process-queues)
    (elpaca `(,@elpaca-order))
#+end_src

*** Use-package
A macro that allows you to isolate package configuration in your .emacs file in a way that is both performance-oriented and, well, tidy.
We use it because it makes package configuration really easy.

With Emacs 29 use-package is now built-in.

This code enables Elpaca integration with use-package.
Elpaca is asynchronous, so we wait here for elpaca-use-package before
processing the rest of this file.
After this, you usually don't need to type :ensure t in every declaration.
Instead, you'll only need to use :ensure nil when you want to explicitly prevent a package from being downloaded.
#+begin_src emacs-lisp
    (elpaca elpaca-use-package
      (require 'elpaca-use-package)
      (elpaca-use-package-mode))
    (elpaca-wait)
    (setq use-package-always-ensure t)
#+end_src

**** Most used parts of use-package
Here is some notes on what each use-package keyword does.
For more check out the use-package documentation to see how powerful it is:
C-h i: g for goto-node: Type (use-package)Top

This code block is not tangled, it is just an example.
#+begin_src emacs-lisp :tangle no
    ;; Configure the 'foo' package
    ;; You can also use (use-package emacs) to customize Emacs with use-package.
    (use-package foo
      :init (message "Before")    ;; execute code Before a package is loaded.
      :config (message "After")   ;; execute code After a package is loaded.
      :custom (foovar t)          ;; Customization of package custom variables same as setq.
      :ensure t                   ;; Ensure the package is installed if it's not already.

      ;; These are also used for lazy loading.
      ;; Don't load the package until these are not true.
      :bind ("C-." . myfunc)      ;; Defer package loading until keybindings are invoked.
      :after (mypackage)          ;; Load package after specified packages have been loaded.
      ;; If you don't know what a hook is:
      ;; C-h i: g for goto-node: Type (emacs)Hooks
      :hook (myhook . myfunc)     ;; Add functions to specified hooks when the package is loaded.

      :command (bar)              ;; Define commands provided by the package to be lazy-loaded.
      :defer t                    ;; Only load this package if it's explicitly needed or a command/hook associated with it is called.
      ;; Install package from source.
      :vc (:url "<You git repo url>"
                :branch "main"
                :rev :newest) ;; Use latest commit
      )
#+end_src

*** Package Async
Simple library for asynchronous processing in Emacs.
#+begin_src emacs-lisp
    (use-package async
      :defer
      :custom
      (dired-async-mode t))
#+end_src

** Good Defaults
#+begin_src emacs-lisp
    (use-package emacs
      :ensure nil
      :custom
      ;; Still needed for terminals
      (menu-bar-mode nil)         ;; Disable the menu bar
      (scroll-bar-mode nil)       ;; Disable the scroll bar
      (tool-bar-mode nil)         ;; Disable the tool bar

      (inhibit-startup-screen t)  ;; Disable welcome screen

      (delete-selection-mode t)   ;; Select text and delete it by typing.
      (electric-indent-mode nil)  ;; Turn off the weird indenting that Emacs does by default.
      (electric-pair-mode t)      ;; Turns on automatic parens pairing

      (blink-cursor-mode nil)     ;; Don't blink cursor
      (global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed
      (use-short-answers t)   ;; Since Emacs 29, `yes-or-no-p' will use `y-or-n-p'

      (dired-kill-when-opening-new-dired-buffer t) ;; Dired don't create new buffer
      (add-hook 'dired-mode-hook #'dired-hide-details-mode)
      (recentf-mode t) ;; Enable recent file mode
      ;;(context-menu-mode t) ;; Right-click menu

      ;;(global-visual-line-mode t)           ;; Enable line wrapping (NOTE: breaks vundo)
      (global-display-line-numbers-mode t)  ;; Display line numbers
      (display-line-numbers-type 'relative) ;; Relative line numbers
      (global-hl-line-mode t)               ;; Highlight current line

      (native-comp-async-report-warnings-errors 'silent) ;; Don't show native comp errors
      (warning-minimum-level :error) ;; Only show errors in warnings buffer

      (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling
      (scroll-conservatively 10) ;; Smooth scrolling
      (scroll-margin 8)

      (pixel-scroll-precision-mode t) ;; Precise pixel scrolling. i.e. smooth scrolling (GUI only)
      (pixel-scroll-precision-use-momentum nil)

      (indent-tabs-mode nil) ;; Only use spaces for indentation
      (tab-width 4)
      (sgml-basic-offset 4) ;; Set Html mode indentation to 4
      (c-ts-mode-indent-offset 4) ;; Fix weird indentation in c-ts (C, C++)
      (go-ts-mode-indent-offset 4) ;; Fix weird indentation in go-ts

      ;; (display-fill-column-indicator-column 80) ;; Set line length indicator to 80 characters
      (whitespace-style '(face tabs tab-mark trailing))

      (make-backup-files nil) ;; Stop creating ~ backup files
      (auto-save-default nil) ;; Stop creating # auto save files
      (delete-by-moving-to-trash t)
      ;; macOS + Norwegian/intl keyboard:
      ;; left Option types symbols like {}[]|, right Option acts as Meta (M-...).
      (ns-option-modifier nil)
      (ns-right-option-modifier 'meta)
      (mac-option-modifier nil)
      (mac-right-option-modifier 'meta)
      :hook
      (prog-mode . hs-minor-mode) ;; Enable folding hide/show globally
      ;; (prog-mode . display-fill-column-indicator-mode) ;; Display line length indicator
      (prog-mode . whitespace-mode)
      :config
      ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
      (setq custom-file (locate-user-emacs-file "custom-vars.el"))
      (load custom-file 'noerror 'nomessage)
      :bind (
             ([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
             ;; Zooming In/Out
             ("C-+" . text-scale-increase)
             ("C--" . text-scale-decrease)
             ("<C-wheel-up>" . text-scale-increase)
             ("<C-wheel-down>" . text-scale-decrease)
             ))
#+end_src

#+RESULTS:
: text-scale-decrease

* Important to load first
Packages that we want to load first so we have them as soon as possible if something breaks.
** Evil Mode
An extensible vi/vim layer for Emacs.
For users who find Emacs's native keybindings less intuitive.
It integrates Vim's editing style into Emacs, giving you the best of both worlds.

If you want to use vim keybindings I left the following comments in the General Keybindings section to which lines to uncomment ;; <- evil

If you don't want to interfere with the original keybindings.
You can also try out [[https://github.com/meow-edit/meow][meow]] which is Yet another modal editing on Emacs.

Notes:
- You can toggle evil mode with C-z.
- To paste without yank select the text and use P. This line is especially for ThePrimeagen :)

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp
    (use-package evil
      :hook (elpaca-after-init . evil-mode)
      :init
      (evil-mode)
      :config
      (evil-set-initial-state 'eat-mode 'insert) ;; Set initial state in eat terminal to insert mode
      ;; (global-set-key [C-backspace] 'evil-delete-backward-word) ;; Make C-backspace less agressive
      :custom
      (evil-want-keybinding nil)    ;; Disable evil bindings in other modes (It's not consistent and not good)
      (evil-want-C-u-scroll t)      ;; Set C-u to scroll up
      (evil-want-C-i-jump nil)      ;; Disables C-i jump
      (evil-undo-system 'undo-redo) ;; C-r to redo
      (evil-want-fine-undo t)
      ;; (evil-respect-visual-line-mode t) ;; Move in wrap lines
      ;; Unmap keys in 'evil-maps. If not done, org-return-follows-link will not work
      :bind (:map evil-motion-state-map
                  ("SPC" . nil)
                  ("RET" . nil)
                  ("TAB" . nil)))
    (use-package evil-collection
      :after evil
      :config
      ;; Setting where to use evil-collection)
      (setq evil-collection-mode-list '(dired ibuffer magit corfu consult info bookmark))
      (evil-collection-init))
#+end_src

** General Keybindings
A keybinding framework to set keybindings easily.

We use general because it gives:
- a convenient method for binding keys.
- easy leader key integration.
- good evil-mode and which-key support.
- a consistent and unified interface for managing keybinds.
And it is also really customizable.

Note: The Leader key is what you will press when you want to access your keybindings:
- Evil normal/visual/motion states: SPC + .  Find file
- Global fallback: C-SPC + .  Find file
#+begin_src emacs-lisp
    (defun start/open-init-file ()
      "Open init.org configuration file"
      (interactive)
      (find-file "~/.config/emacs/init.org"))

    (defun start/reload-config()
      "Reload Emacs config"
      (interactive)
      (load-file "~/.config/emacs/init.el"))

    (defun start/copy-file-path ()
      "Copy the current buffer file path to the kill ring."
      (interactive)
      (if-let ((path (buffer-file-name)))
          (progn
            (kill-new (file-truename path))
            (message "Copied path: %s" (file-truename path)))
        (message "Current buffer is not visiting a file.")))

    (defun start/split-window-below-and-focus ()
      "Split the current window below and move focus to it."
      (interactive)
      (split-window-below)
      (windmove-down))

    (defun start/split-window-right-and-focus ()
      "Split the current window right and move focus to it."
      (interactive)
      (split-window-right)
      (windmove-right))

    (defvar start/font-scale-repeat-map
      (let ((map (make-sparse-keymap)))
        (define-key map (kbd "+") #'start/font-scale-increase)
        (define-key map (kbd "-") #'start/font-scale-decrease)
        (define-key map (kbd "=") #'start/font-scale-reset)
        map)
      "Transient keymap used to repeat font scaling commands.")

    (defun start/font-scale-increase ()
      "Increase font size and keep font scaling keys active."
      (interactive)
      (text-scale-increase 1)
      (set-transient-map start/font-scale-repeat-map t))

    (defun start/font-scale-decrease ()
      "Decrease font size and keep font scaling keys active."
      (interactive)
      (text-scale-decrease 1)
      (set-transient-map start/font-scale-repeat-map t))

    (defun start/font-scale-reset ()
      "Reset font size and keep font scaling keys active."
      (interactive)
      (text-scale-set 0)
      (set-transient-map start/font-scale-repeat-map t))

    (use-package general
      :after (evil) ;; <- evil
      :config
      (general-evil-setup) ;; <- evil
      ;; Set up 'SPC' as the Evil leader key
      (general-create-definer start/leader-keys
        :states '(normal visual motion) ;; <- evil
        :keymaps 'override
        :prefix "SPC"
        :global-prefix "C-SPC") ;; Global fallback from non-evil states

      (start/leader-keys
        "." '(find-file :wk "Find file")
        "," '(embark-act :wk "Embark act")
        "TAB" '(comment-line :wk "Comment lines")
        "q" '(:ignore t :wk "Quit")

        ;; Projectile
        "p" '(projectile-command-map :wk "Projectile")
        "s p" '(projectile-discover-projects-in-search-path :wk "Search for projects"))

      (start/leader-keys
        "f" '(:ignore t :wk "Files")
        "f f" '(find-file :wk "Find file")
        "f s" '(save-buffer :wk "Save file")
        "f S" '(write-file :wk "Save file as")
        "f r" '(consult-recent-file :wk "Recent files")
        "f c" '(start/open-init-file :wk "Open config")
        "f d" '(dired-jump :wk "Dired at file")
        "f y" '(start/copy-file-path :wk "Copy file path"))

      (start/leader-keys
        "m" '(:ignore t :wk "Bookmarks & Registers")
        ;; Registers
        "m s" '(consult-register :wk "Consult register")
        "m k" '(jump-to-register :wk "Jump to register")
        "m e" '(point-to-register :wk "Point to register")
        ;; Bookmarks
        "m a" '(bookmark-set :wk "Bookmark Set")
        "m d" '(bookmark-jump :wk "Bookmark Jump")
        "m r" '(bookmark-delete :wk "Bookmark Delete")
        "m R" '(bookmark-delete-all :wk "Bookmark Delete All")
        "m l" '(bookmark-bmenu-list :wk "Bookmark bmenu list")
        "m c" '(consult-bookmark :wk "Consult Bookmark"))

      (start/leader-keys
        "s" '(:ignore t :wk "Search")
        "s c" '(start/open-init-file :wk "Open init file")
        "s r" '(consult-recent-file :wk "Search recent files")
        "s f" '(consult-fd :wk "Search files with fd")
        "s g" '(consult-ripgrep :wk "Search with ripgrep")
        "s l" '(consult-line :wk "Search line")
        "s i" '(consult-imenu :wk "Search Imenu buffer locations")) ;; This one is really cool

      (start/leader-keys
        "b" '(:ignore t :wk "Buffers & Dired")
        "b s" '(consult-buffer :wk "Switch buffer")
        "b k" '(kill-current-buffer :wk "Kill current buffer")
        "b i" '(ibuffer :wk "Ibuffer")
        "b n" '(next-buffer :wk "Next buffer")
        "b p" '(previous-buffer :wk "Previous buffer")
        "b r" '(revert-buffer :wk "Reload buffer")
        "b v" '(dired :wk "Open dired")
        "b j" '(dired-jump :wk "Dired jump to current"))

      (start/leader-keys
        "w" '(:ignore t :wk "Windows")
        "w w" '(other-window :wk "Other window")
        "w s" '(split-window-below :wk "Split below")
        "w v" '(split-window-right :wk "Split right")
        "w S" '(start/split-window-below-and-focus :wk "Split below + focus")
        "w V" '(start/split-window-right-and-focus :wk "Split right + focus")
        "w d" '(delete-window :wk "Delete window")
        "w o" '(delete-other-windows :wk "Delete others")
        "w +" '(start/font-scale-increase :wk "Increase font")
        "w -" '(start/font-scale-decrease :wk "Decrease font")
        "w =" '(start/font-scale-reset :wk "Reset font")
        "w h" '(windmove-left :wk "Move left")
        "w j" '(windmove-down :wk "Move down")
        "w k" '(windmove-up :wk "Move up")
        "w l" '(windmove-right :wk "Move right")
        "w H" '(windmove-swap-states-left :wk "Window left")
        "w J" '(windmove-swap-states-down :wk "Window down")
        "w K" '(windmove-swap-states-up :wk "Window up")
        "w L" '(windmove-swap-states-right :wk "Window right"))

      (start/leader-keys
        "c" '(:ignore t :wk "Code")
        "c e" '(eglot-reconnect :wk "Eglot Reconnect")
        "c d" '(eldoc-doc-buffer :wk "Eldoc Buffer")
        "c h" '(eldoc-box-help-at-point :wk "Eldoc Box")
        "c f" '(eglot-format :wk "Eglot Format")
        "c g" '(gptel :wk "GPTel")

        "c l" '(consult-flymake :wk "Consult Flymake")
        "c n" '(flymake-goto-next-error :wk "Flymake next error")
        "c p" '(flymake-goto-prev-error :wk "Flymake previous error")

        "c a" '(eglot-code-actions :wk "Eglot code actions")
        "c r" '(eglot-rename :wk "Eglot Rename")
        "c i" '(xref-find-definitions :wk "Find definition")
        "c s" '(xref-find-references :wk "Find references"))

      (start/leader-keys
        "e" '(:ignore t :wk "Elisp")
        "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
        "e r" '(eval-region :wk "Evaluate elisp in region"))

      (start/leader-keys
        "g" '(:ignore t :wk "Git")
        "g s" '(magit-status :wk "Magit status"))

      (start/leader-keys
        "r" '(:ignore t :wk "Reload & Packages") ;; To get more help use C-h commands (describe variable, function, etc.)
        ;; Mason.el
        "r m" '(mason-manager :wk "Mason manager")
        "r i" '(mason-install :wk "Mason install")
        ;; Elpaca
        "r p" '(elpaca-manager :wk "Elpaca manager")
        "r f" '(elpaca-fetch-all :wk "Elpaca fetch updates")
        "r g" '(elpaca-merge-all :wk "Elpaca merge updates")
        "r u" '(elpaca-update-all :wk "Elpaca update all")
        "r l" '(elpaca-log :wk "Elpaca log")

        "r q" '(save-buffers-kill-emacs :wk "Quit Emacs and Daemon")
        "r r" '(start/reload-config :wk "Reload Emacs config"))

  (start/leader-keys
    "q q" '(save-buffers-kill-emacs :wk "Quit Emacs"))

      (start/leader-keys
        "t" '(:ignore t :wk "Toggle")
        "t e" '(eat :wk "Eat terminal")
        "t v" '(vterm :wk "Vterm")
        "t V" '(multi-vterm :wk "Multi-vterm")
        "t s" '(start/toggle-spelling :wk "Toggle spelling")
        "t t" '(visual-line-mode :wk "Toggle truncated lines (wrap)")
        "t l" '(display-line-numbers-mode :wk "Toggle line numbers"))
      )

    ;; Fix general.el leader key not working instantly in messages buffer with evil mode
    (use-package emacs
      :ensure nil
      :after (evil general)
      :hook (elpaca-after-init
             . (lambda ()
                 (when-let ((messages-buffer (get-buffer "*Messages*")))
                   (with-current-buffer messages-buffer
                     (evil-normalize-keymaps))))))
#+end_src

*** Creating keybindings the built in way
If you want to use the built in methods I recommend using these ones:

This code block is not tangled, it is just an example.
#+begin_src emacs-lisp :tangle no
    (define-key KEYMAP KEY DEF)
    (global-set-key KEY COMMAND)
    (use-package :bind (  ))
#+end_src
To read more about using the built in methods, check out this awesome article from [[https://www.masteringemacs.org/article/mastering-key-bindings-emacs][masteringemacs]].

** Undo
Undotree like setup.

Undo Fu: Simple, stable linear undo with redo for Emacs.
Undo-fu-session: Persistent undo history
Vundo: Visualizes undo history.

If you want to use this. Don't forget to add keybindings for undu-fu and vundo.
Evil users don't need to add keybindings for undo-fu just change evil-undo-system to undo-fu.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    (use-package undo-fu
      :defer
      :config
      ;; Increase undo history limits to reduce likelihood of data loss
      (setq undo-limit (* 1024 1024 64)          ;; 64mb  (default is 160kb)
            undo-strong-limit (* 1024 1024 96)   ;; 96mb  (default is 240kb)
            undo-outer-limit (* 1024 1024 960))) ;; 960mb (default is 24mb)

    (use-package undo-fu-session
      :hook (elpaca-after-init . undo-fu-session-global-mode)
      :custom (undo-fu-session-incompatible-files '("\\.gpg$" "/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
      :config
      (when (executable-find "zstd")
        ;; There are other algorithms available, but zstd is the fastest, and speed
        ;; is our priority within Emacs
        (setq undo-fu-session-compression 'zst)))

    (use-package vundo
      :defer
      :custom
      (vundo-glyph-alist vundo-unicode-symbols)
      (vundo-compact-display t))
#+end_src

* Appearance
** Fonts
Set your base font and default font size here.
#+begin_src emacs-lisp
    (defvar start/font-family "Cascadia Mono")
    (defvar start/font-size 160) ;; 120 = 12pt
    (defvar start/font-weight 'medium)
    (defvar start/font-line-spacing 0.12)

    (defun start/apply-fonts (&optional frame)
      "Apply base font settings to FRAME or current frame."
      (with-selected-frame (or frame (selected-frame))
        (when (display-graphic-p)
          (set-face-attribute 'default nil
                              :family start/font-family
                              :height start/font-size
                              :weight start/font-weight)))
      (setq-default line-spacing start/font-line-spacing))

    ;; Apply now and for new frames (important for emacsclient/daemon).
    (start/apply-fonts)
    (add-hook 'after-make-frame-functions #'start/apply-fonts)
#+end_src

** Frame Size
Set default GUI frame size as a ratio of your monitor workarea.
#+begin_src emacs-lisp
    (defvar start/frame-size-ratio 0.80)

    (defun start/apply-frame-size (&optional frame)
      "Resize FRAME to `start/frame-size-ratio' of monitor workarea and center it."
      (let ((frame (or frame (selected-frame))))
        (when (display-graphic-p frame)
          (let* ((workarea (and (fboundp 'frame-monitor-attribute)
                                (frame-monitor-attribute 'workarea frame)))
                 (wx (or (nth 0 workarea) 0))
                 (wy (or (nth 1 workarea) 0))
                 (ww (or (nth 2 workarea) (display-pixel-width frame)))
                 (wh (or (nth 3 workarea) (display-pixel-height frame)))
                 (target-w (floor (* ww start/frame-size-ratio)))
                 (target-h (floor (* wh start/frame-size-ratio)))
                 (left (+ wx (/ (- ww target-w) 2)))
                 (top (+ wy (/ (- wh target-h) 2))))
            (set-frame-size frame target-w target-h t)
            (set-frame-position frame left top)))))

    ;; Apply on startup and for new frames (emacsclient/daemon).
    (add-hook 'window-setup-hook #'start/apply-frame-size)
    (add-hook 'after-make-frame-functions #'start/apply-frame-size)
#+end_src

** Set Theme
Set gruvbox theme, if you want some themes try out doom-themes.
Use consult-theme to easily try out themes (*Epilepsy* Warning).
#+begin_src emacs-lisp
    (use-package gruvbox-theme
      :config
      (setq gruvbox-bold-constructs t)
      (load-theme 'gruvbox-dark-medium t)) ;; We need to add t to trust this package
#+end_src

** Transparency
With Emacs version 29, true transparency has been added.
#+begin_src emacs-lisp
    (add-to-list 'default-frame-alist '(alpha-background . 90)) ;; For all new frames henceforth

    ;; Transparency in terminal
    (defun start/tui-enable-transparency ()
      (unless (display-graphic-p (selected-frame))
        (set-face-background 'default "unspecified-bg" (selected-frame))))

    (add-hook 'window-setup-hook 'start/tui-enable-transparency)
#+end_src

** Doom Modeline
A fancy, fast and customizable mode-line.
#+begin_src emacs-lisp
    (use-package doom-modeline
      :custom
      (doom-modeline-height 25) ;; Set modeline height
      :hook (elpaca-after-init . doom-modeline-mode))
#+end_src

** Nerd Icons
This is an icon set that can be used with dired, ibuffer and other Emacs packages.
Don't forget nerd-icons-install-fonts to install the resource fonts.

We use nerd-icons because it supports both GUI and TUI unlike all-the-icons.
Also Doom modeline requires nerd icons.
#+begin_src emacs-lisp
    (use-package nerd-icons :defer)

    (use-package nerd-icons-dired
      :hook (dired-mode . nerd-icons-dired-mode))

    (use-package nerd-icons-ibuffer
      :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

* Development
** Projectile
Project interaction library for Emacs.

Emacs has a built in project manager called project.el, but we don't use it.
You can try it out with the keybinds under C-x p because project.el does not require any special setup to use.

We use projectile because it:
- supports more features and project types.
- has better integration with projects.
- has better documentation.
- is developed faster.
More [[https://docs.projectile.mx/projectile/projectile_vs_project.html][reasons]] to use projectile.

You can also make the [[https://github.com/karthink/consult-dir][consult-dir]] package list all the directories you [[https://github.com/MiniApollo/config/blob/main/emacs/init.org#consult-dir][specified]] and search from them like in tmux-sessionizer.
#+begin_src emacs-lisp
    (use-package projectile
      :hook (elpaca-after-init . projectile-mode)
      :config
      (projectile-mode)
      :custom
      ;; (projectile-auto-discover nil) ;; Disable auto search for better startup times ;; Search with a keybind
      (projectile-run-use-comint-mode t) ;; Interactive run dialog when running projects inside emacs (like giving input)
      (projectile-switch-project-action #'projectile-dired) ;; Open dired when switching to a project
      (projectile-project-search-path '("~/projects/" "~/work/" ("~/github" . 1)))) ;; . 1 means only search the first subdirectory level for projects
#+end_src

** Eglot
Built in Emacs client for the Language Server Protocol.
We use Eglot because it is fast and minimal.
For more: C-h i: g: (eglot)Top

Eglot does not automatically download LSP servers. It requires separate download.
The easiest way to install LSP servers is with a package manager like mason.el.

If you can't use a package manager you can do the following:
- Download the server (e.g. from github)
- Add the binary/executable to your path.
- Or customize the eglot-server-programs list.
To control how a LSP server is started customize the eglot-server-programs list.

There are many alternative LSP clients, one of them is LSP-mode.
Which has more features and supports automatic language server installation.
But it's bigger, so it has more moving parts.

We don't use it because Eglot is more than enough for most people.
If you want to use LSP mode check out their [[https://emacs-lsp.github.io/lsp-mode/][documentation]] or the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] page for more information.
#+begin_src emacs-lisp
    (use-package eglot
      :ensure nil ;; Don't install eglot because it's now built-in
      :hook ((c-mode c-ts-mode c++-mode c++-ts-mode
                     lua-mode lua-ts-mode
                     python-mode python-ts-mode
                     elixir-mode elixir-ts-mode heex-ts-mode
                     typescript-ts-mode tsx-ts-mode)
             . eglot-ensure)
      :custom
      ;; Good default
      (eglot-events-buffer-size 0) ;; No event buffers (LSP server logs)
      (eglot-autoshutdown t);; Shutdown unused servers.
      (eglot-report-progress nil) ;; Disable LSP server logs (Don't show lsp messages at the bottom, java)
      :config
      ;; Use basedpyright for Python via uv.
      ;; uv will cache the tool after the first run.
      (setf (alist-get '(python-mode python-ts-mode)
                       eglot-server-programs
                       nil nil #'equal)
            '("uv" "tool" "run" "--from" "basedpyright"
              "basedpyright-langserver" "--stdio"))
      ;; Use Expert as Elixir LSP server. See: https://expert-lsp.org/docs/editors#emacs
      (setf (alist-get '(elixir-mode heex-ts-mode elixir-ts-mode)
                       eglot-server-programs
                       nil nil #'equal)
            '("expert" "--stdio")))
#+end_src

** Mason.el
Package manager for LSP, DAP, linters, and more for the Emacs Operating System.
I waited so long for a package like this.
If you plan to use something like LSP-mode don't forget to remove this.
#+begin_src emacs-lisp
    (use-package mason
      :hook (elpaca-after-init . mason-ensure))
#+end_src

** Eldoc Box
Childframe docs for eldoc/Eglot.
#+begin_src emacs-lisp
    (use-package eldoc-box
      :commands (eldoc-box-help-at-point))
#+end_src

** Sideline-flymake
Show flymake errors with sideline.
#+begin_src emacs-lisp
    (use-package sideline-flymake
      :hook (flymake-mode . sideline-mode)
      :custom
      (sideline-flymake-display-mode 'line) ;; Show errors on the current line
      (sideline-backends-right '(sideline-flymake)))
#+end_src

** Yasnippet
A template system for Emacs. And yasnippet-snippets is a snippet collection package.
To use it write out the full keyword (or use autocompletion) and press Tab.
#+begin_src emacs-lisp
    (use-package yasnippet
      :hook (prog-mode . yas-minor-mode))

    (use-package yasnippet-snippets :defer)

    (defun start/corfu-yas-tab-handler ()
      "Prioritize corfu over yasnippet when yasnippet is active"
      (interactive)
      ;; There is no direct way to get if corfu is currently displayed so we watch the completion index
      (if (> corfu--index -1)
          (corfu-complete)
        (yas-next-field-or-maybe-expand)
        ))
    (use-package emacs
      :ensure nil
      :after (yasnippet corfu)
      :bind
      (:map yas-keymap
            ("TAB" . start/corfu-yas-tab-handler)))
#+end_src

** Snippy
VSCode/LSP snippet support for Emacs with Yasnippet.
Uses friendly snippets.
Developed by me.
Note: If you want to use a different package manager you may need to adjust the package recipe.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    (use-package snippy
      :ensure (:host github :repo "MiniApollo/snippy" :branch "main")
      :hook (elpaca-after-init . global-snippy-minor-mode)
      :custom
      (snippy-global-languages '("global")) ;; Recomended
      ;; Optional
      ;; (snippy-install-dir (expand-file-name <Your location>))
      ;; Use different snippet collections
      ;; (snippy-source '("Your git repo" . "my-snippets-dir"))
      :config
      (snippy-install-or-update-snippets)) ;; Autoupdate git repo
#+end_src

** Tree-Sitter
A parser generator tool and an incremental parsing library.
Check out TJ's [[https://www.youtube.com/watch?v=09-9LltqWLY][video]] to learn why you should use it.

With Emacs 29 Tree-Sitter is now built-in. You may need to compile Emacs from source to have it enabled.
You also need to have a compiler installed so Emacs can compile the parsers into a shared library.
For more info about how to use Tree-Sitter check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][masteringemacs]] article.

Using Tree-Sitter is somewhat hacky because it requires you to:
- manually manage a source list of the parsers you want to use.
- remap the major modes you want to use.
You can also use treesit-auto, but it is updated quite slowly so we don't use it.

To explore the current buffer's syntax tree, use the treesit-explore-mode command.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp
    (setq treesit-language-source-alist
          '((bash "https://github.com/tree-sitter/tree-sitter-bash")
            (cmake "https://github.com/uyha/tree-sitter-cmake")
            (c "https://github.com/tree-sitter/tree-sitter-c")
            (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
            (css "https://github.com/tree-sitter/tree-sitter-css")
            (elixir "https://github.com/elixir-lang/tree-sitter-elixir")
            (elisp "https://github.com/Wilfred/tree-sitter-elisp")
            (gdscript "https://github.com/PrestonKnopp/tree-sitter-gdscript")
            (go "https://github.com/tree-sitter/tree-sitter-go")
            (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
            (heex "https://github.com/phoenixframework/tree-sitter-heex")
            (html "https://github.com/tree-sitter/tree-sitter-html")
            (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
            (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
            (json "https://github.com/tree-sitter/tree-sitter-json")
            (make "https://github.com/alemuller/tree-sitter-make")
            (markdown "https://github.com/ikatyang/tree-sitter-markdown")
            (python "https://github.com/tree-sitter/tree-sitter-python")
            (rust "https://github.com/tree-sitter/tree-sitter-rust")
            (toml "https://github.com/tree-sitter/tree-sitter-toml")
            (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
            (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
            (vue "https://github.com/ikatyang/tree-sitter-vue")
            (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

    (defun start/install-treesit-grammars ()
      "Install missing treesitter grammars"
      (interactive)
      (dolist (grammar treesit-language-source-alist)
        (let ((lang (car grammar)))
          (unless (treesit-language-available-p lang)
            (treesit-install-language-grammar lang)))))

    ;; Run manually when needed: M-x start/install-treesit-grammars
    ;; Avoid installing grammars at every startup.

    ;; Optionally, add any additional mode remappings not covered by defaults
    (setq major-mode-remap-alist
          '((yaml-mode . yaml-ts-mode)
            (sh-mode . bash-ts-mode)
            (c-mode . c-ts-mode)
            (c++-mode . c++-ts-mode)
            (css-mode . css-ts-mode)
            (elixir-mode . elixir-ts-mode)
            (heex-mode . heex-ts-mode)
            (python-mode . python-ts-mode)
            (mhtml-mode . html-ts-mode)
            (javascript-mode . js-ts-mode)
            (js-json-mode . json-ts-mode)
            (typescript-mode . typescript-ts-mode)
            (conf-toml-mode . toml-ts-mode)
            (gdscript-mode . gdscript-ts-mode)
            ))
    (setq treesit-font-lock-level 3)

    ;; Or if there is no built in mode
    (use-package cmake-ts-mode :ensure nil :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))
    (use-package elixir-ts-mode :ensure nil :mode ("\\.ex\\'" "\\.exs\\'"))
    (use-package go-mod-ts-mode :ensure nil :mode "\\.mod\\'")
    (use-package heex-ts-mode :ensure nil :mode ("\\.[hl]?eex\\'"))
    (use-package lua-ts-mode :ensure nil :mode "\\.lua\\'")
    (use-package rust-ts-mode :ensure nil :mode "\\.rs\\'")
    (use-package typescript-ts-mode :ensure nil :mode "\\.ts\\'")
    (use-package tsx-ts-mode :ensure nil :mode "\\.tsx\\'")
    (use-package yaml-ts-mode :ensure nil :mode ("\\.yaml\\'" "\\.yml\\'"))
#+end_src

*** Writing your own syntax highlight with treesitter
You can easily write your own font locking with treesitter

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    ;; https://github.com/emacs-mirror/emacs/blob/master/admin/notes/tree-sitter/starter-guide
    (use-package go-ts-mode
      :ensure nil
      :mode "\\.go\\'"
      :config
      (defvar start/ts-font-lock-settings
        (treesit-font-lock-rules
         :language 'go ;; What language
         :feature 'function-highlight ;; A unique feature name that we can toggle.
         `(
           ;; Function calls
           (call_expression
            function: (selector_expression
                       field: (field_identifier) @font-lock-function-call-face)) ;; Use 'describe-face' to find faces
           ;; Property values
           (argument_list
            (selector_expression
             field: (field_identifier) @font-lock-property-use-face))
           (expression_list
            (selector_expression
             field: (field_identifier) @font-lock-property-use-face))
           ;; ((Treesit patern) @defface_Settings)
           ))
        "Go-ts-mode settings, fix not highlighting function calls and property values")

      (add-hook 'go-ts-mode-hook
                (lambda () (setq-local treesit-font-lock-settings
                                       (append treesit-font-lock-settings
                                               start/ts-font-lock-settings))))
      )
#+end_src

** Language modes
Emacs contains many “editing modes” that alter its basic behavior in
useful ways. These are divided into “major modes” and “minor modes”.
For more: C-h i: g: (emacs)Modes

Some programming languages require the installation of specific modes to fully integrate and function within Emacs.
These packages are often necessary for features like syntax highlighting, code formatting, linting, and language-specific features.

*** Lua mode
Example, how to setup a language mode.
Use SPC tab (or C-SPC tab as fallback) to uncomment the lines.
# #+begin_src emacs-lisp
#     (use-package lua-mode
#       :mode "\\.lua\\'") ;; Only start in a lua file
# #+end_src

*** Org Mode
One of the things that Emacs is loved for.
Once you've used it for a bit, you'll understand why people love it. Even reading about it can be inspiring!
For example, this document is effectively the source code and descriptions bound into the one document,
much like the literate programming ideas that Donald Knuth made famous.

We use an Org mode document for our Emacs configuration because it provides:
- Better organization: It lets us structure with outlines, headings, and tags.
- Literate Documentation: It's a document, not just source code.
- Fast Navigation: Quickly jump to sections with something like Imenu.

If you consider using org mode even more. Check out the [[https://github.com/minad/org-modern][org-modern]] package.
It makes org mode really beautiful.
Don't forget to remove org-superstar if you want to use it.

For templates use C-c C-,
Much easier than org-tempo
#+begin_src emacs-lisp
    (use-package org
      :ensure nil
      :custom
      (org-edit-src-content-indentation 4) ;; Set src block automatic indent to 4 instead of 2.
      (org-return-follows-link t)   ;; Sets RETURN key in org-mode to follow links
      :hook
      (org-mode . org-indent-mode) ;; Indent text
      )
#+end_src

**** Table of Contents
#+begin_src emacs-lisp
    (use-package toc-org
      :commands toc-org-enable
      :hook (org-mode . toc-org-mode))
#+end_src

**** Org Superstar
Prettify headings and plain lists in Org mode. Modern version of org-bullets.
#+begin_src emacs-lisp
    (use-package org-superstar
      :after org
      :hook (org-mode . org-superstar-mode))
#+end_src

**** Org Modern
Modern Org UI package.
#+begin_src emacs-lisp
    (use-package org-modern
      :hook ((org-mode . org-modern-mode)
             (org-agenda-finalize . org-modern-agenda)))
#+end_src

** Terminal
*** Eat
Eat(Emulate A Terminal) is a terminal emulator within Emacs.
It's more portable and less overhead for users over like vterm or eshell.
We setup eat with eshell, if you want to use bash, zsh etc., check out their git [[https://codeberg.org/akib/emacs-eat][repository]] how to do it.

If you want a faster and more responsive terminal emulator try out vterm.
#+begin_src emacs-lisp
    (use-package eat
      :defer
      :hook ('eshell-load-hook #'eat-eshell-mode))
#+end_src

*** Vterm
Fast terminal emulator inside Emacs.
#+begin_src emacs-lisp
    (use-package vterm
      :commands (vterm vterm-other-window)
      :custom
      (vterm-max-scrollback 10000))
#+end_src

*** Multi-vterm
Manage multiple vterm buffers.
#+begin_src emacs-lisp
    (use-package multi-vterm
      :after vterm
      :commands (multi-vterm multi-vterm-next multi-vterm-prev))
#+end_src

*** Exec-path-from-shell
Make Emacs use the $PATH set up by the user's shell
#+begin_src emacs-lisp
    (use-package exec-path-from-shell
      :hook (elpaca-after-init . exec-path-from-shell-initialize))
#+end_src

* Multi File Example
** Adding the lisp directory to load-path
Adds the lisp directory to Emacs's load path to search for elisp files.
This is necessary because Emacs does not search the entire user-emacs-directory.
The directory name can be anything, just add it to the load-path.
#+begin_src emacs-lisp
    ;; (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
#+end_src

** Sourcing the files
To use the elisp files we need to load it.
Notes:
- Don't forget the file and the provide name needs to be the same.
- When naming elisp files, functions, it is recommended to use a group name (e.g. init-, start- or any custom name), so it does not get mixed up with other names, functions.
#+begin_src emacs-lisp
    ;; (require 'start-multiFileExample)
#+end_src

** Using the file
And now we can use everything from that file.
#+begin_src emacs-lisp
    ;; (start/hello)
#+end_src

* Version Control
** Magit
Complete text-based user interface to Git.
#+begin_src emacs-lisp
    (use-package transient
      :defer
      :config
      (define-key transient-map (kbd "<escape>") 'transient-quit-one)) ;; Make escape quit magit prompts

    (use-package magit
      :defer
      :custom (magit-diff-refine-hunk (quote all)) ;; Shows inline diff
      :config
      (setopt magit-format-file-function #'magit-format-file-nerd-icons) ;; Magit nerd icons
      )
#+end_src

** Diff-hl
Highlights uncommitted changes on the left side of the window (area also known as the "gutter"), allows you to jump between and revert them selectively.
#+begin_src emacs-lisp
    (use-package diff-hl
      :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
             (magit-post-refresh . diff-hl-magit-post-refresh)
             (elpaca-after-init . global-diff-hl-mode)))
#+end_src

* Completion
** Corfu
Enhances in-buffer completion with a small completion popup.
Corfu is a small package, which relies on the Emacs completion facilities and concentrates on providing a polished completion.
For more configuration options check out their [[https://github.com/minad/corfu][git repository]].
Notes:
- To enter Orderless field separator, use M-SPC.
#+begin_src emacs-lisp
    (use-package corfu
      ;; Optional customizations
      :custom
      (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
      (corfu-auto t)                 ;; Enable auto completion
      (corfu-auto-prefix 2)          ;; Minimum length of prefix for auto completion.
      (corfu-popupinfo-mode t)       ;; Enable popup information
      (corfu-popupinfo-delay 0.5)    ;; Lower popup info delay to 0.5 seconds from 2 seconds
      (corfu-separator ?\s)          ;; Orderless field separator, Use M-SPC to enter separator
      ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
      ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
      ;; (corfu-preview-current nil)    ;; Disable current candidate preview
      ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
      ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
      ;; (corfu-scroll-margin 5)        ;; Use scroll margin
      (completion-ignore-case t)

      ;; Emacs 30 and newer: Disable Ispell completion function.
      ;; Try `cape-dict' as an alternative.
      (text-mode-ispell-word-completion nil)

      ;; Enable indentation+completion using the TAB key.
      ;; `completion-at-point' is often bound to M-TAB.
      (tab-always-indent 'complete)

      (corfu-preview-current nil) ;; Don't insert completion without confirmation
      ;; Recommended: Enable Corfu globally.  This is recommended since Dabbrev can
      ;; be used globally (M-/).  See also the customization variable
      ;; `global-corfu-modes' to exclude certain modes.
      :init
      (global-corfu-mode))

    (use-package nerd-icons-corfu
      :after corfu
      :init (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

** Cape
Provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI.

We merge capfs together so they appear together in the completion list.
The ones not merged will display separately (Only their list will show up in the completion list).
Order matters. Since these functions run in sequence, the first one to return a list will prevent others from running.
Due to technical details, not all Capfs can be merged successfully (e.g cape-file).

Notes:
- Be aware when adding Capfs (Completion-at-point-functions) to the list since each of the Capfs adds a small runtime cost.
Read the [[https://github.com/minad/cape#configuration][configuration section]] in Cape's readme for more information.
#+begin_src emacs-lisp
    (use-package yasnippet-capf :defer)

    (defun start/setup-capfs ()
      "Configure completion backends"
      ;; Take care when adding Capfs to the list since each of the Capfs adds a small runtime cost.
      (let ((merge-backends (append
                             (list
                              #'cape-keyword      ;; Keyword completion
                              ;; #'cape-abbrev       ;; Complete abbreviation
                              #'cape-dabbrev      ;; Complete word from current buffers
                              ;; #'cape-line         ;; Complete entire line from current buffer
                              ;; #'cape-history      ;; Complete from Eshell, Comint or minibuffer history
                              ;; #'cape-dict         ;; Dictionary completion (Needs Dictionary file installed)
                              ;; #'cape-tex          ;; Complete Unicode char from TeX command, e.g. \hbar
                              ;; #'cape-sgml         ;; Complete Unicode char from SGML entity, e.g., &alpha
                              ;; #'cape-rfc1345      ;; Complete Unicode char using RFC 1345 mnemonics
                              )
                             (when (fboundp 'snippy-capf)
                               (list #'snippy-capf)) ;; Vscode snippets (optional Snippy)
                             (list #'yasnippet-capf) ;; Yasnippet snippets
                             ))
            (seperate-backends (list
                                #'cape-file ;; Path completion
                                #'cape-elisp-block ;; Complete elisp in Org or Markdown mode
                                )))
        ;; Remove keyword completion in git commits
        (when (derived-mode-p 'git-commit-mode)
          (setq merge-backends (remq #'cape-keyword merge-backends)))

        ;; Add Elisp symbols only in Elisp modes
        (when (derived-mode-p 'emacs-lisp-mode 'ielm-mode)
          (setq merge-backends (cons #'cape-elisp-symbol merge-backends))) ;; Emacs Lisp code (functions, variables)

        ;; Add Eglot to the front of the list if it's active
        (when (bound-and-true-p eglot--managed-mode)
          (setq merge-backends (cons #'eglot-completion-at-point merge-backends)))

        ;; Create the super-capf and set it buffer-locally
        (setq-local completion-at-point-functions
                    (append
                     seperate-backends
                     (list (apply #'cape-capf-super merge-backends)))
                    )))

    (use-package cape
      :after (corfu)
      :init
      ;; Add to the global default value of `completion-at-point-functions' which is
      ;; used by `completion-at-point'.  The order of the functions matters, the
      ;; first function returning a result wins.  Note that the list of buffer-local
      ;; completion functions takes precedence over the global list.

      ;; Seperate function needed, because we use setq-local (everything is replaced)
      (add-hook 'eglot-managed-mode-hook #'start/setup-capfs)
      (add-hook 'prog-mode-hook #'start/setup-capfs)
      (add-hook 'text-mode-hook #'start/setup-capfs))
#+end_src

** Orderless
Completion style that divides the pattern into space-separated components and matches candidates that match all of the components in any order.
Recommended for packages like vertico, corfu.
#+begin_src emacs-lisp
    (use-package orderless
      :defer
      :custom
      (completion-styles '(orderless basic))
      (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** Vertico and Marginalia
- Vertico: Provides a performant and minimalistic vertical completion UI based on the default completion system.
- Savehist: Saves completion history.
- Marginalia: Adds extra metadata for completions in the margins (like descriptions).
- Nerd-icons-completion: Adds icons to completion candidates using the built in completion metadata functions.

We use these packages because they use Emacs native functions. Unlike Ivy or Helm.
One alternative is ivy and counsel, check out the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] for more inforomation.
#+begin_src emacs-lisp
    (use-package vertico
      :hook (elpaca-after-init . vertico-mode)
      ;; Vim keybinds
      :bind (:map vertico-map
                 ("C-j" . vertico-next)
                 ("C-k" . vertico-previous)
                 ("C-u" . vertico-scroll-down)
                 ("C-d" . vertico-scroll-up))
      :custom
      (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
      )

    (savehist-mode) ;; Enables save history mode

    (use-package marginalia
      :after vertico
      :config
      (marginalia-mode))

    (use-package nerd-icons-completion
      :after marginalia
      :config
      (nerd-icons-completion-mode)
      :hook
      (marginalia-mode . nerd-icons-completion-marginalia-setup))
#+end_src

** Embark
Emacs Mini-Buffer Actions Rooted in Keymaps. Right click like menu for Emacs.
#+begin_src emacs-lisp
    (use-package embark :defer)
    (use-package embark-consult
      :hook
      (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Jinx
Enchanted Spell Checker.
Don't forget to add keybindings.

Jinx can cause performance problems in large markdown files.
#+begin_src emacs-lisp
    (defun start/setup-ispell-fallback ()
      "Configure flyspell with hunspell/aspell when jinx is unavailable."
      (let ((spell-program (or (executable-find "hunspell")
                               (executable-find "aspell"))))
        (if spell-program
            (progn
              (setq ispell-program-name spell-program
                    ispell-dictionary "en_US")
              (add-hook 'text-mode-hook #'flyspell-mode)
              (add-hook 'prog-mode-hook #'flyspell-prog-mode)
              (message "Spelling backend: %s + flyspell"
                       (file-name-nondirectory spell-program)))
          (message "No spelling backend found. Install enchant (for jinx) or hunspell/aspell."))))

    (defun start/enable-spelling ()
      "Enable jinx globally, fallback to flyspell if jinx fails."
      (condition-case err
          (if (require 'jinx nil t)
              (progn
                (setq jinx-languages "en_US nb_NO")
                (global-jinx-mode 1)
                (message "Spelling backend: jinx"))
            (start/setup-ispell-fallback))
        (error
         (message "Jinx unavailable (%s), using flyspell fallback."
                  (error-message-string err))
         (start/setup-ispell-fallback))))

    (defun start/toggle-spelling ()
      "Toggle spelling in the current buffer."
      (interactive)
      (cond
       ((bound-and-true-p jinx-mode)
        (jinx-mode -1)
        (message "Jinx disabled in buffer"))
       ((fboundp 'jinx-mode)
        (jinx-mode 1)
        (message "Jinx enabled in buffer"))
       ((bound-and-true-p flyspell-mode)
        (flyspell-mode -1)
        (message "Flyspell disabled in buffer"))
       (t
        (flyspell-mode 1)
        (message "Flyspell enabled in buffer"))))

    (defun start/correct-word-at-point ()
      "Correct spelling at point using jinx or ispell."
      (interactive)
      (cond
       ((fboundp 'jinx-correct) (call-interactively #'jinx-correct))
       ((fboundp 'ispell-word) (call-interactively #'ispell-word))
       (t (user-error "No spelling command available"))))

    (use-package jinx
      :defer t
      :commands (jinx-mode jinx-correct global-jinx-mode))

    (use-package emacs
      :ensure nil
      :hook (elpaca-after-init . start/enable-spelling))
#+end_src

** GPTel
General LLM interface for Emacs.
#+begin_src emacs-lisp
    (use-package gptel
      :commands (gptel))
#+end_src

** Copilot
GitHub Copilot integration.
#+begin_src emacs-lisp
    (use-package track-changes
      :defer)

    (use-package copilot
      :ensure (:host github :repo "copilot-emacs/copilot.el")
      :after track-changes
      :hook (prog-mode . copilot-mode)
      :bind (:map copilot-completion-map
                  ("<tab>" . copilot-accept-completion)
                  ("TAB" . copilot-accept-completion)
                  ("C-<tab>" . copilot-accept-completion-by-word)
                  ("C-TAB" . copilot-accept-completion-by-word)))
#+end_src

* Other packages
All the package setups that don't need much tweaking.
** Consult
Provides search and navigation commands based on the Emacs completion function.
Telescope for Emacs.
Check out their [[https://github.com/minad/consult][git repository]] for more awesome functions.
#+begin_src emacs-lisp
    (use-package consult
      ;; Enable automatic preview at point in the *Completions* buffer. This is
      ;; relevant when you use the default completion UI.
      :hook (completion-list-mode . consult-preview-at-point-mode)
      :init
      ;; Optionally configure the register formatting. This improves the register
      ;; preview for `consult-register', `consult-register-load',
      ;; `consult-register-store' and the Emacs built-ins.
      (setq register-preview-delay 0.5
            register-preview-function #'consult-register-format)

      ;; Optionally tweak the register preview window.
      ;; This adds thin lines, sorting and hides the mode line of the window.
      (advice-add #'register-preview :override #'consult-register-window)

      ;; Use Consult to select xref locations with preview
      (setq xref-show-xrefs-function #'consult-xref
            xref-show-definitions-function #'consult-xref)
      :config
      ;; Optionally configure preview. The default value
      ;; is 'any, such that any key triggers the preview.
      ;; (setq consult-preview-key 'any)
      ;; (setq consult-preview-key "M-.")
      ;; (setq consult-preview-key '("S-<down>" "S-<up>"))

      ;; For some commands and buffer sources it is useful to configure the
      ;; :preview-key on a per-command basis using the `consult-customize' macro.
      ;; (consult-customize
      ;; consult-theme :preview-key '(:debounce 0.2 any)
      ;; consult-ripgrep consult-git-grep consult-grep
      ;; consult-bookmark consult-recent-file consult-xref
      ;; consult--source-bookmark consult--source-file-register
      ;; consult--source-recent-file consult--source-project-recent-file
      ;; :preview-key "M-."
      ;; :preview-key '(:debounce 0.4 any))

      ;; By default `consult-project-function' uses `project-root' from project.el.
      ;; Optionally configure a different project root function.
       ;;;; 1. project.el (the default)
      ;; (setq consult-project-function #'consult--default-project--function)
       ;;;; 2. vc.el (vc-root-dir)
      ;; (setq consult-project-function (lambda (_) (vc-root-dir)))
       ;;;; 3. locate-dominating-file
      ;; (setq consult-project-function (lambda (_) (locate-dominating-file "." ".git")))
       ;;;; 4. projectile.el (projectile-project-root)
      (autoload 'projectile-project-root "projectile")
      (setq consult-project-function (lambda (_) (projectile-project-root)))
       ;;;; 5. No project support
      ;; (setq consult-project-function nil)
      )
#+end_src

** Helpful
An alternative to the built-in Emacs help that provides much more contextual information.
#+begin_src emacs-lisp
    (use-package helpful
      :bind
      ;; Note that the built-in `describe-function' includes both functions
      ;; and macros. `helpful-function' is functions only, so we provide
      ;; `helpful-callable' as a drop-in replacement.
      ("C-h f" . helpful-callable)
      ("C-h v" . helpful-variable)
      ("C-h k" . helpful-key)
      ("C-h x" . helpful-command)
      )
#+end_src

** Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.
With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
    (use-package diminish :defer)
#+end_src

** Rainbow Delimiters
Adds colors to brackets.
#+begin_src emacs-lisp
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Hl-todo
Highlight TODO keywords.
#+begin_src emacs-lisp
    (use-package hl-todo
      :hook
      ((prog-mode yaml-ts-mode) . hl-todo-mode)
      :config
      ;; From doom emacs
      (setq hl-todo-highlight-punctuation ":"
            hl-todo-keyword-faces
            '(;; For reminders to change or add something at a later date.
              ("TODO" warning bold)
              ;; For code (or code paths) that are broken, unimplemented, or slow,
              ;; and may become bigger problems later.
              ("FIXME" error bold)
              ;; For code that needs to be revisited later, either to upstream it,
              ;; improve it, or address non-critical issues.
              ("REVIEW" font-lock-keyword-face bold)
              ;; For code smells where questionable practices are used
              ;; intentionally, and/or is likely to break in a future update.
              ("HACK" font-lock-constant-face bold)
              ;; For sections of code that just gotta go, and will be gone soon.
              ;; Specifically, this means the code is deprecated, not necessarily
              ;; the feature it enables.
              ("DEPRECATED" font-lock-doc-face bold)
              ;; Extra keywords commonly found in the wild, whose meaning may vary
              ;; from project to project.
              ("NOTE" success bold)
              ("BUG" error bold)
              ("XXX" font-lock-constant-face bold)))
      )
#+end_src

** Indent-guide
Show indentation.
#+begin_src emacs-lisp
    (use-package indent-guide
      :hook
      (prog-mode . indent-guide-mode)
      :config
      (setq indent-guide-char "│")) ;; Set the character used for the indent guide.
#+end_src

** Which-Key
Which-key is a helper utility for keychords (which key to press).
#+begin_src emacs-lisp
    (use-package which-key
      :ensure nil ;; Don't install which-key because it's now built-in
      :hook (elpaca-after-init . which-key-mode)
      :diminish
      :custom
      (which-key-side-window-location 'bottom)
      (which-key-sort-order #'which-key-key-order-alpha) ;; Same as default, except single characters are sorted alphabetically
      (which-key-sort-uppercase-first nil)
      (which-key-add-column-padding 1) ;; Number of spaces to add to the left of each column
      (which-key-min-display-lines 6)  ;; Increase the minimum lines to display because the default is only 1
      (which-key-idle-delay 0.8)       ;; Set the time delay (in seconds) for the which-key popup to appear
      (which-key-max-description-length 25)
      (which-key-allow-imprecise-window-fit nil)) ;; Fixes which-key window slipping out in Emacs Daemon
#+end_src

** Ws-butler
Removes whitespace from the ends of lines.
#+begin_src emacs-lisp
    (use-package ws-butler
      :hook (elpaca-after-init . ws-butler-global-mode))
#+end_src

** Esup
Emacs Start Up Profiler.
Benchmark Emacs Startup time: M-x esup

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    (use-package esup
      :defer
      :custom
      (esup-depth 0))
#+end_src

** ag
#+begin_src emacs-lisp
(use-package ag
  :commands (ag ag-project))
#+end_src

#+RESULTS:
: [nil 27046 46812 912610 nil elpaca-process-queues nil nil 0 nil]
